name       : gphoto2
version    : 2.5.28
release    : 8
source     :
    - https://github.com/gphoto/gphoto2/releases/download/v2.5.28/gphoto2-2.5.28.tar.gz : 54097ee429f57a9f076a814590f777cebbc837879fe7b16e41b2615e347f6ae0
homepage   : http://www.gphoto.com/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Software for accessing digital cameras
description: |
    The gPhoto2 project is a universal, free application and library framework that lets you download images from several different digital camera models, including the newer models with USB connections.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(popt)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
