name       : gphoto2
version    : 2.5.23
release    : 5
source     :
    - https://github.com/gphoto/gphoto2/archive/gphoto2-2_5_23-release.tar.gz : dc78b7f8a88803937301d157b5b32cd45f6defcc771564438a477a7fb05f4489
homepage   : http://www.gphoto.com/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Software for accessing digital cameras
description: |
    The gPhoto2 project is a universal, free application and library framework that lets you download images from several different digital camera models, including the newer models with USB connections.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(popt)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
