name       : gphoto2
version    : 2.5.17
release    : 2
source     :
    - https://kent.dl.sourceforge.net/project/gphoto/gphoto/2.5.17/gphoto2-2.5.17.tar.bz2 : aa571039240c68a053be710ca41645aed0239fa2f0b737b8ec767fef29e3544f
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Software for accessing digital cameras
description: |
    The gPhoto2 project is a universal, free application and library
    framework that lets you download images from several different
    digital camera models, including the newer models with USB
    connections.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(popt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
