name       : gphoto2
version    : 2.5.20
release    : 4
source     :
    - https://github.com/gphoto/gphoto2/archive/gphoto2-2_5_20-release.tar.gz : 8d8f0f473b56118015b83f55c0ca806c0c1545003ce0e9ecbb514e417e5dbf99
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Software for accessing digital cameras
description: |
    The gPhoto2 project is a universal, free application and library
    framework that lets you download images from several different
    digital camera models, including the newer models with USB
    connections.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(popt)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
