name       : gphoto2
version    : 2.5.20
release    : 3
source     :
    - https://kent.dl.sourceforge.net/project/gphoto/gphoto/2.5.20/gphoto2-2.5.20.tar.bz2 : a36f03b50a8f040f185cbc757f957f03dc05a9210907199e6919ef3f970248f6
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Software for accessing digital cameras
description: |
    The gPhoto2 project is a universal, free application and library
    framework that lets you download images from several different
    digital camera models, including the newer models with USB
    connections.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(popt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
