name       : gphoto2
version    : 2.5.15
release    : 1
source     :
    - https://kent.dl.sourceforge.net/project/gphoto/gphoto/2.5.15/gphoto2-2.5.15.tar.bz2 : ae571a227983dc9997876702a73af5431d41f287ea0f483cda897c57a6084a77
license    : GPL-2.0
component  : multimedia.graphics
summary    : Software for accessing digital cameras
description: |
    The gPhoto2 project is a universal, free application and library
    framework that lets you download images from several different
    digital camera models, including the newer models with USB
    connections.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(popt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
